/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.ulbra.view;

import br.ulbra.DAO.VeiculosDAO;
import br.ulbra.entity.Veiculos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s.lucas
 */
public class FrCarros extends javax.swing.JFrame {

    /** Creates new form FrCarros */
    public FrCarros() 
                throws SQLException {
        initComponents();
        controlarBt(1);
        readJTable();
        this.setLocationRelativeTo(null);
    }
    public void limpar(){
        edCodVeic.setText(null);
        edTipoVeic.setText(null);
        edMarcaVeic.setText(null);
        edModeloVeic.setText(null);
        edAnoVeic.setText(null);
        edCorVeic.setText(null);
        edPlacaVeic.setText(null);  
        edKmVeic.setText(null);
}
    public void controlarBt(
            int op) {
        switch (op) {
            case 1:
                pnCadVeic.setVisible(false);
                limpar();
                break;
            case 2:
                pnCadVeic.setVisible(true);
                btSalvarVeic.setEnabled(true);
                btAlterarVeic.setEnabled(false);
                btExcluirVeic.setEnabled(false);
                break;
            case 3:
                pnCadVeic.setVisible(true);
                btAlterarVeic.setEnabled(true);
                btExcluirVeic.setEnabled(true);
                btSalvarVeic.setEnabled(false);
                break;
        }
        this.pack();
    }
    
    public void readJTable() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbVeiculos.getModel();
        modelo.setNumRows(0);
        VeiculosDAO vdao = new VeiculosDAO();
        for (Veiculos v : vdao.read()) {
            modelo.addRow(new Object[]{
                v.getcodVeic(),
                v.gettipoVeic(),
                v.getmarcaVeic(),
                v.getmodeloVeic(),
                v.getanoFabVeic(),
                v.getcorVeic(),
                v.getplacaVeic(),
                v.getkmVeic()
            });
        }
    }
    public void readJTableForDesc(String nome) throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbVeiculos.getModel();
        modelo.setNumRows(0);
        VeiculosDAO vdao = new VeiculosDAO();
        for (Veiculos v : vdao.readForDesc(nome)) {
            modelo.addRow(new Object[]{
                v.getcodVeic(),
                v.gettipoVeic(),
                v.getmarcaVeic(),
                v.getmodeloVeic(),
                v.getanoFabVeic(),
                v.getcorVeic(),
                v.getplacaVeic(),
                v.getkmVeic()
            });
        }
    }
    
    
    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        edPesquisaVeic = new javax.swing.JTextField();
        btPesquisarVeic = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVeiculos = new javax.swing.JTable();
        pnCadVeic = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        edCodVeic = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        edTipoVeic = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        edMarcaVeic = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        edModeloVeic = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edAnoVeic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        edCorVeic = new javax.swing.JTextField();
        btSalvarVeic = new javax.swing.JButton();
        btAlterarVeic = new javax.swing.JButton();
        btExcluirVeic = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        edPlacaVeic = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        edKmVeic = new javax.swing.JTextField();
        btNovoVeic = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(113, 140, 92));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CADASTRO DE VEÍCULOS");

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel2.setText("PESQUISA");

        edPesquisaVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edPesquisaVeicActionPerformed(evt);
            }
        });

        btPesquisarVeic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/18213_magnifying glass_zoom_find_search_icon (1).png"))); // NOI18N
        btPesquisarVeic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btPesquisarVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarVeicActionPerformed(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tbVeiculos.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        tbVeiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "COD", "Tipo", "Marca", "Modelo", "Ano de Fabricação", "Cor", "Placa", "KM's"
            }
        ));
        tbVeiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbVeiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbVeiculos);

        pnCadVeic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel3.setText("COD");

        edCodVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel4.setText("TIPO");

        edTipoVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel5.setText("MARCA");

        edMarcaVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel6.setText("MODELO");

        edModeloVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel7.setText("ANO DE FABRICAÇÃO");

        edAnoVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel8.setText("COR");

        edCorVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N

        btSalvarVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        btSalvarVeic.setText("SALVAR");
        btSalvarVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarVeicActionPerformed(evt);
            }
        });

        btAlterarVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        btAlterarVeic.setText("ALTERAR");
        btAlterarVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarVeicActionPerformed(evt);
            }
        });

        btExcluirVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        btExcluirVeic.setText("EXCLUIR");
        btExcluirVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirVeicActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel9.setText("PLACA");

        edPlacaVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        jLabel10.setText("KM's");

        edKmVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N

        javax.swing.GroupLayout pnCadVeicLayout = new javax.swing.GroupLayout(pnCadVeic);
        pnCadVeic.setLayout(pnCadVeicLayout);
        pnCadVeicLayout.setHorizontalGroup(
            pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadVeicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCadVeicLayout.createSequentialGroup()
                        .addComponent(btSalvarVeic)
                        .addGap(125, 125, 125)
                        .addComponent(btAlterarVeic)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btExcluirVeic))
                    .addGroup(pnCadVeicLayout.createSequentialGroup()
                        .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCadVeicLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edAnoVeic))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCadVeicLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edCodVeic))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCadVeicLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(edMarcaVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnCadVeicLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edPlacaVeic)))
                        .addGap(18, 18, 18)
                        .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnCadVeicLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edTipoVeic))
                            .addGroup(pnCadVeicLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edModeloVeic, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                            .addGroup(pnCadVeicLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edCorVeic))
                            .addGroup(pnCadVeicLayout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edKmVeic)))))
                .addContainerGap())
        );
        pnCadVeicLayout.setVerticalGroup(
            pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCadVeicLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edCodVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(edTipoVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(edMarcaVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(edModeloVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edAnoVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(edCorVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(edPlacaVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(edKmVeic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btExcluirVeic)
                    .addGroup(pnCadVeicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btSalvarVeic)
                        .addComponent(btAlterarVeic)))
                .addContainerGap())
        );

        btNovoVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        btNovoVeic.setText("NOVO");
        btNovoVeic.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btNovoVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoVeicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnCadVeic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btNovoVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addComponent(edPesquisaVeic))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btPesquisarVeic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edPesquisaVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisarVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btNovoVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnCadVeic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void edPesquisaVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edPesquisaVeicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edPesquisaVeicActionPerformed

    private void btPesquisarVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarVeicActionPerformed
        try {
            readJTableForDesc(edPesquisaVeic.getText());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro: "+ex.getMessage());
        }
    }//GEN-LAST:event_btPesquisarVeicActionPerformed

    private void tbVeiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbVeiculosMouseClicked
        if (tbVeiculos.getSelectedRow() != -1) {
            edCodVeic.setText(tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 0).toString());
            edTipoVeic.setText(tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 1).toString());
            edMarcaVeic.setText(tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 2).toString());
            edModeloVeic.setText(tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 3).toString());
            edAnoVeic.setText(tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 4).toString());
            edCorVeic.setText(tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 5).toString());
            edPlacaVeic.setText(tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 6).toString());
            edKmVeic.setText(tbVeiculos.getValueAt(tbVeiculos.getSelectedRow(), 7).toString());
            
            controlarBt(3);

        }
    }//GEN-LAST:event_tbVeiculosMouseClicked

    private void btSalvarVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarVeicActionPerformed
        Veiculos v = new Veiculos();
        try {
            VeiculosDAO vd = new VeiculosDAO();
            v.settipoVeic(edTipoVeic.getText());
            v.setmarcaVeic(edMarcaVeic.getText());
            v.setmodeloVeic(edModeloVeic.getText());
            v.setanoFabVeic(Integer.parseInt(edAnoVeic.getText()));
            v.setcorVeic(edCorVeic.getText());
            v.setplacaVeic(edPlacaVeic.getText());
            v.setkmVeic(Integer.parseInt(edKmVeic.getText()));
            vd.create(v);
            readJTable();
            controlarBt(1);
}
       catch (SQLException ex) {
            JOptionPane.showMessageDialog(null,"Erro:"+ex.getMessage());
}
    }//GEN-LAST:event_btSalvarVeicActionPerformed

    private void btNovoVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoVeicActionPerformed
        controlarBt(2);
    }//GEN-LAST:event_btNovoVeicActionPerformed

    private void btAlterarVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarVeicActionPerformed
         Veiculos v = new Veiculos();
        try {
        VeiculosDAO vd = new VeiculosDAO();
            v.setcodVeic(Integer.parseInt(edCodVeic.getText()));
            v.settipoVeic(edTipoVeic.getText());
            v.setmarcaVeic(edMarcaVeic.getText());
            v.setmodeloVeic(edModeloVeic.getText());
            v.setanoFabVeic(Integer.parseInt(edAnoVeic.getText()));
            v.setcorVeic(edCorVeic.getText());
            v.setplacaVeic(edPlacaVeic.getText());
            v.setkmVeic(Integer.parseInt(edKmVeic.getText()));
            vd.update(v);
            readJTable();
            controlarBt(1);
       
}       catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro: " + e.getMessage());
}
    }//GEN-LAST:event_btAlterarVeicActionPerformed

    private void btExcluirVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirVeicActionPerformed
        Veiculos v = new Veiculos();
        try {
        VeiculosDAO vd = new VeiculosDAO();
        if(JOptionPane.showConfirmDialog(null,"Tem certeza que você deseja excluir o cadastro deste veículo?","Excluir Registro",JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION){
            v.setcodVeic(Integer.parseInt(edCodVeic.getText()));
            vd.delete(v);
            readJTable();
            controlarBt(1);
}       else{
            JOptionPane.showMessageDialog(null, "Exclusão Cancelada com sucesso!");
}
}       catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro: " + ex.getMessage());
}
    }//GEN-LAST:event_btExcluirVeicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrCarros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrCarros().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrCarros.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarVeic;
    private javax.swing.JButton btExcluirVeic;
    private javax.swing.JButton btNovoVeic;
    private javax.swing.JButton btPesquisarVeic;
    private javax.swing.JButton btSalvarVeic;
    private javax.swing.JTextField edAnoVeic;
    private javax.swing.JTextField edCodVeic;
    private javax.swing.JTextField edCorVeic;
    private javax.swing.JTextField edKmVeic;
    private javax.swing.JTextField edMarcaVeic;
    private javax.swing.JTextField edModeloVeic;
    private javax.swing.JTextField edPesquisaVeic;
    private javax.swing.JTextField edPlacaVeic;
    private javax.swing.JTextField edTipoVeic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnCadVeic;
    private javax.swing.JTable tbVeiculos;
    // End of variables declaration//GEN-END:variables

}
