/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.DAO.VeiculosDAO;
import br.ulbra.entity.Veiculos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author s.lucas
 */
public class FrConsVeicOA extends javax.swing.JFrame {

    /**
     * Creates new form FrConsulta1
     */
    public FrConsVeicOA() throws SQLException {
        initComponents();
        readConsVeicAZ();
        this.setLocationRelativeTo(null);
    }
    
    public void readConsVeicAZ() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbConsVeic.getModel();
        modelo.setNumRows(0);
        VeiculosDAO vdao = new VeiculosDAO();
        for (Veiculos v : vdao.readAZ()) {
            modelo.addRow(new Object[]{
                v.getcodVeic(),
                v.gettipoVeic(),
                v.getmarcaVeic(),
                v.getmodeloVeic(),
                v.getplacaVeic()
            });
        }
    }
    public void readConsVeicZA() throws SQLException {
        DefaultTableModel modelo = (DefaultTableModel) tbConsVeic.getModel();
        modelo.setNumRows(0);
        VeiculosDAO vdao = new VeiculosDAO();
        for (Veiculos v : vdao.readZA()) {
            modelo.addRow(new Object[]{
                v.getcodVeic(),
                v.gettipoVeic(),
                v.getmarcaVeic(),
                v.getmodeloVeic(),
                v.getplacaVeic()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btConsCresVeic = new javax.swing.JButton();
        btConsDecresVeic = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbConsVeic = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(113, 140, 92));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Medium", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CONSULTA DE VEÍCULOS POR OA");

        btConsCresVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        btConsCresVeic.setText("A-Z");
        btConsCresVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsCresVeicActionPerformed(evt);
            }
        });

        btConsDecresVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        btConsDecresVeic.setText("Z-A");
        btConsDecresVeic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConsDecresVeicActionPerformed(evt);
            }
        });

        tbConsVeic.setFont(new java.awt.Font("Franklin Gothic Medium", 0, 11)); // NOI18N
        tbConsVeic.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "COD", "Tipo", "Marca", "Modelo", "Placa"
            }
        ));
        jScrollPane1.setViewportView(tbConsVeic);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(btConsCresVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btConsDecresVeic, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btConsDecresVeic)
                    .addComponent(btConsCresVeic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btConsCresVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsCresVeicActionPerformed
        try {
            readConsVeicAZ();
        } catch (SQLException ex) {
            Logger.getLogger(FrConsVeicOA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConsCresVeicActionPerformed

    private void btConsDecresVeicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConsDecresVeicActionPerformed
        try {
            readConsVeicZA();
        } catch (SQLException ex) {
            Logger.getLogger(FrConsVeicOA.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btConsDecresVeicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrConsVeicOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrConsVeicOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrConsVeicOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrConsVeicOA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrConsUsuOA().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FrConsUsuOA.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConsCresVeic;
    private javax.swing.JButton btConsDecresVeic;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbConsVeic;
    // End of variables declaration//GEN-END:variables
}
